In [161]:
import tensorflow as tf
import numpy as np
import os
from tensorflow import keras
import matplotlib.pyplot as plt

In [15]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)

In [6]:
X

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [11]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [9]:
for x in X:
    print(x)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [10]:
for x in dataset:
    print(x)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [20]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset = dataset.repeat(3).batch(7)
for x in dataset:
    print(x)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [22]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset = dataset.repeat(3).batch(7,drop_remainder=True)
for x in dataset:
    print(x)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


Or we can modify the dataset on our own function:

In [23]:
dataset= dataset.map(lambda x : x *2)
for x in dataset:
    print(x)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)


In [24]:
dataset= dataset.apply(tf.data.experimental.unbatch())
for x in dataset:
    print(x)

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=

In [26]:
dataset = dataset.filter(lambda x : x <10)
for x in dataset:
    print(x)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [27]:
for item in dataset.take(3):
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


### Shuffle the data

In [43]:
dataset = tf.data.Dataset.range(100).repeat(3)
dataset = dataset.shuffle(buffer_size=2,seed=42).batch(90)
for item in dataset:
    print(item)

tf.Tensor(
[ 1  2  0  3  5  4  6  7  8 10  9 11 13 14 15 12 17 16 19 20 18 22 21 24
 23 25 26 27 29 28 30 31 33 34 35 36 32 38 37 39 40 42 43 41 44 46 45 48
 49 47 50 52 51 53 55 54 57 56 59 60 61 58 62 64 63 65 66 68 67 70 69 71
 73 72 75 74 77 78 76 79 80 82 81 83 84 85 86 88 87 89], shape=(90,), dtype=int64)
tf.Tensor(
[90 91 93 94 92 95 97 98 96  0 99  2  1  3  5  4  6  8  9 10 11 12 13 14
  7 15 17 18 16 20 21 22 23 19 25 26 24 28 27 30 31 29 33 34 35 32 36 38
 39 37 40 41 42 43 45 44 46 48 47 49 50 51 53 52 54 56 57 55 58 59 60 62
 63 61 65 66 67 64 69 70 68 71 73 74 75 72 77 78 76 79], shape=(90,), dtype=int64)
tf.Tensor(
[80 82 83 84 85 86 87 88 81 90 91 92 89 94 93 95 96 97 99  0 98  2  3  1
  4  5  6  7  9 10 11  8 13 14 12 16 17 15 18 20 21 22 19 24 25 23 26 27
 29 30 28 32 33 31 35 36 34 38 37 39 40 42 41 43 44 46 47 48 49 50 51 52
 53 45 55 56 54 57 59 60 58 62 61 63 65 64 67 68 66 70], shape=(90,), dtype=int64)
tf.Tensor(
[71 72 69 74 73 76 75 78 79 77 80 82 83 81 85 84 8

### split the califonia house price data

In [74]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
scaler.fit(X_train)
X_mean = scaler.mean_
X_std = scaler.scale_

In [48]:
def save_to_multiple_csv_files(data, name_prefix, header=None, n_parts=10):
    housing_dir = os.path.join("datasets", "housing")
    os.makedirs(housing_dir, exist_ok=True)
    path_format = os.path.join(housing_dir, "my_{}_{:02d}.csv")

    filepaths = []
    m = len(data)
    for file_idx, row_indices in enumerate(np.array_split(np.arange(m), n_parts)):
        part_csv = path_format.format(name_prefix, file_idx)
        filepaths.append(part_csv)
        with open(part_csv, "wt", encoding="utf-8") as f:
            if header is not None:
                f.write(header)
                f.write("\n")
            for row_idx in row_indices:
                f.write(",".join([repr(col) for col in data[row_idx]]))
                f.write("\n")
    return filepaths

In [53]:
train_data = np.c_[X_train, y_train]
valid_data = np.c_[X_valid, y_valid]
test_data = np.c_[X_test, y_test]
header_cols = housing.feature_names + ["MedianHouseValue"]
header = ",".join(header_cols)

train_filepaths = save_to_multiple_csv_files(train_data, "train", header, n_parts=20)
valid_filepaths = save_to_multiple_csv_files(valid_data, "valid", header, n_parts=10)
test_filepaths = save_to_multiple_csv_files(test_data, "test", header, n_parts=10)

List the data

In [60]:
import pandas as pd

pd.read_csv(train_filepaths[0]).head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  3.5214      15.0  3.049945   1.106548      1447.0  1.605993     37.63   
1  5.3275       5.0  6.490060   0.991054      3464.0  3.443340     33.69   
2  3.1000      29.0  7.542373   1.591525      1328.0  2.250847     38.44   
3  7.1736      12.0  6.289003   0.997442      1054.0  2.695652     33.55   
4  2.0549      13.0  5.312457   1.085092      3297.0  2.244384     33.93   

   Longitude  MedianHouseValue  
0    -122.43             1.442  
1    -117.39             1.687  
2    -122.98             1.621  
3    -117.70             2.621  
4    -116.93             0.956

Process the data

In [64]:
filepath_dataset = tf.data.Dataset.list_files(train_filepaths, seed=42)
for filepath in filepath_dataset:
    print(filepath)

tf.Tensor(b'datasets/housing/my_train_05.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_16.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_01.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_17.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_00.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_14.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_10.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_02.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_12.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_19.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_07.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_09.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_13.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_15.csv', shape=(), dtype=string)
tf.Ten

In [65]:
n_readers = 5
dataset = filepath_dataset.interleave(
    lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
    cycle_length=n_readers)

##### introducing decode_csv
basically, it's just filling NaN with the record_defaults

In [76]:
record_defaults=[0, np.nan, tf.constant(np.nan, dtype=tf.float64), "Hello", tf.constant([])]
parsed_fields = tf.io.decode_csv('1,2,3,4,5', record_defaults)
parsed_fields

[<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'4'>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>]

In [77]:

parsed_fields = tf.io.decode_csv(',,,,5', record_defaults)
parsed_fields

[<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=nan>,
 <tf.Tensor: shape=(), dtype=float64, numpy=nan>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>]

##### Now go back to the business:

In [81]:
n_inputs = 8 # X_train.shape[-1]

@tf.function
def preprocess(line):
    defs = [0.] * n_inputs + [tf.constant([], dtype=tf.float32)]
    fields = tf.io.decode_csv(line, record_defaults=defs)
    x = tf.stack(fields[:-1])   # stack the input 
    y = tf.stack(fields[-1:])   # stack the target
    return (x - X_mean) / X_std, y

In [79]:
preprocess(b'4.2083,44.0,5.3232,0.9171,846.0,2.3370,37.47,-122.2,2.782')


(<tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([ 0.16579157,  1.216324  , -0.05204565, -0.39215982, -0.5277444 ,
        -0.2633488 ,  0.8543046 , -1.3072058 ], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.782], dtype=float32)>)

In [80]:
def csv_reader_dataset(filepaths, repeat=1, n_readers=5,
                       n_read_threads=None, shuffle_buffer_size=10000,
                       n_parse_threads=5, batch_size=32):
    dataset = tf.data.Dataset.list_files(filepaths).repeat(repeat)   # make the file list
    dataset = dataset.interleave(                                    # combine severa files together
        lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
        cycle_length=n_readers, num_parallel_calls=n_read_threads)
    dataset = dataset.shuffle(shuffle_buffer_size)                   # shuffle the files
    dataset = dataset.map(preprocess, num_parallel_calls=n_parse_threads)   # process
    dataset = dataset.batch(batch_size)                                     # pick one 
    return dataset.prefetch(1)

### Using the dataset with tf.keras

In [82]:
train_set = csv_reader_dataset(train_filepaths, repeat=None)
valid_set = csv_reader_dataset(valid_filepaths)
test_set = csv_reader_dataset(test_filepaths)

In [84]:
a = tf.data.Dataset.range(10)

Building up the layers

In [98]:
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

model = keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1),
])

In [99]:
model.compile(loss="mse", optimizer=keras.optimizers.SGD(lr=1e-3))

In [100]:
batch_size = 32
model.fit(train_set, steps_per_epoch=len(X_train) // batch_size, epochs=10,
          validation_data=valid_set)


Train for 362 steps
Epoch 1/10
362/362 [==============================] - 2s 6ms/step - loss: 1.6275 - val_loss: 3.1570
Epoch 2/10
362/362 [==============================] - 1s 4ms/step - loss: 0.7338 - val_loss: 0.6500
Epoch 3/10
362/362 [==============================] - 1s 4ms/step - loss: 0.6280 - val_loss: 0.6004
Epoch 4/10
362/362 [==============================] - 2s 4ms/step - loss: 0.5855 - val_loss: 0.6051
Epoch 5/10
362/362 [==============================] - 1s 4ms/step - loss: 0.5604 - val_loss: 0.7180
Epoch 6/10
362/362 [==============================] - 1s 4ms/step - loss: 0.5598 - val_loss: 0.5180
Epoch 7/10
362/362 [==============================] - 1s 4ms/step - loss: 0.5322 - val_loss: 0.5443
Epoch 8/10
362/362 [==============================] - 2s 4ms/step - loss: 0.5083 - val_loss: 0.4805
Epoch 9/10
362/362 [==============================] - 1s 4ms/step - loss: 0.4995 - val_loss: 0.4711
Epoch 10/10
362/362 [==============================] - 1s 4ms/step - loss: 0.494

In [101]:
model.evaluate(test_set, steps=len(X_test) // batch_size)

161/161 [==============================] - 0s 3ms/step - loss: 0.4782


0.4781885970823513

In [102]:
new_set = test_set.map(lambda X, y: X) # we could instead just pass test_set, Keras would ignore the labels
X_new = X_test
model.predict(new_set, steps=len(X_new) // batch_size)

array([[2.8291953],
       [2.7574086],
       [1.9006665],
       ...,
       [2.8839815],
       [1.597825 ],
       [0.9231253]], dtype=float32)

In [103]:
for m in dir(tf.data.Dataset):
    if not (m.startswith("_") or m.endswith("_")):
        func = getattr(tf.data.Dataset, m)
        if hasattr(func, "__doc__"):
            print("● {:21s}{}".format(m + "()", func.__doc__.split("\n")[0]))

● apply()              Applies a transformation function to this dataset.
● as_numpy_iterator()  Returns an iterator which converts all elements of the dataset to numpy.
● batch()              Combines consecutive elements of this dataset into batches.
● cache()              Caches the elements in this dataset.
● concatenate()        Creates a `Dataset` by concatenating the given dataset with this dataset.
● element_spec()       The type specification of an element of this dataset.
● enumerate()          Enumerates the elements of this dataset.
● filter()             Filters this dataset according to `predicate`.
● flat_map()           Maps `map_func` across this dataset and flattens the result.
● from_generator()     Creates a `Dataset` whose elements are generated by `generator`.
● from_tensor_slices() Creates a `Dataset` whose elements are slices of the given tensors.
● from_tensors()       Creates a `Dataset` with a single element, comprising the given tensors.
● interleave()      

## Preprocessing the input features

In [104]:
import os
import tarfile
import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

In [105]:
fetch_housing_data()

In [106]:
import pandas as pd

def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path, "housing.csv")
    return pd.read_csv(csv_path)

In [107]:

housing = load_housing_data()
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

#### Numerical data

In [109]:
class Standarlization(keras.layers.Layer):
    def adapt(self, datasample):
        self.means_ = np.mean(datasample,axis=0,keepdims=True)
        self.std_ = np.std(datasample,axis=0,keepdims=True)
    def call(self,inputs):
        return (inputs-self.means_)/(self.stds_+keras.backend.epsilon())

In [ ]:
std_layer = Standarlization()
std_layer.adapt(datasample)

#### Categorical Feature

In [127]:
vocab = ['<1H OCEAN','INLAND','NEAR OCEEAN','NEAR BAY','ISLAND']
indices = tf.range(len(vocab),dtype=tf.int64)
table_init = tf.lookup.KeyValueTensorInitializer(vocab,indices)     #Building up a lookup table
num_oov = 2 
table = tf.lookup.StaticVocabularyTable(table_init,num_oov)         #Building up a lookup table, with 2 out-of-vocabulary

In [126]:
categories  = tf.constant(['NEAR BAY','DESERT','INLAND','INLAND'])
cat_indices = table.lookup(categories)
cat_onehot = tf.one_hot(cat_indices,depth=len(vocab)+num_oov)  # this's a func, need to use tf.layers.Lambda for use

In [124]:
cat_onehot

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

## Word Embedding 

In [128]:
embedding_dim =2

In [131]:
embed_init = tf.random.uniform([len(vocab)+num_oov,embedding_dim])
embedding_matrix = tf.Variable(embed_init)

In [132]:
embedding_matrix

<tf.Variable 'Variable:0' shape=(7, 2) dtype=float32, numpy=
array([[0.7402308 , 0.33938193],
       [0.5692506 , 0.44811392],
       [0.29285502, 0.4260056 ],
       [0.62890387, 0.691061  ],
       [0.30925727, 0.89236605],
       [0.66396606, 0.30541587],
       [0.8724164 , 0.1025728 ]], dtype=float32)>

In [134]:
categories  = tf.constant(['NEAR BAY','DESERT','INLAND','INLAND'])
cat_indices = table.lookup(categories)
cat_indices

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 5, 1, 1])>

In [135]:
tf.nn.embedding_lookup(embedding_matrix,cat_indices)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.62890387, 0.691061  ],
       [0.66396606, 0.30541587],
       [0.5692506 , 0.44811392],
       [0.5692506 , 0.44811392]], dtype=float32)>

Or using the embedding matrix

In [138]:
embedding = keras.layers.Embedding(input_dim=len(vocab)+num_oov,output_dim=embedding_dim)
embedding(cat_indices)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.01379195, -0.02229853],
       [ 0.0406372 , -0.0277444 ],
       [-0.01294596,  0.04118674],
       [-0.01294596,  0.04118674]], dtype=float32)>

### Putting everything together

In [142]:
regular_input = keras.layers.Input(shape=[8])
categories = keras.layers.Input(shape=[],dtype=tf.string)
cat_indices = keras.layers.Lambda(lambda x : table.lookup(x))(categories)
cat_embed = embedding = keras.layers.Embedding(input_dim=len(vocab)+num_oov,output_dim=embedding_dim)(cat_indices)
encoded_inputs = keras.layers.concatenate([regular_input,cat_embed])
outputs = keras.layers.Dense(1)(encoded_inputs)
model = keras.models.Model(inputs=[regular_input,categories],outputs=[outputs])

# TF datasets Project

In [155]:
import tensorflow_datasets as tfds

In [156]:
dataset = tdfs.load(name='mnist')

In [157]:
mnist_train,mnist_test = dataset['train'],dataset['test']

In [165]:
plt.figure(figsize=(6,3))
mnist_train = mnist_train.repeat(5).batch(32).prefetch(1)
for item in mnist_train:
    images = item["image"]
    labels = item["label"]
    for index in range(5):
        plt.subplot(1, 5, index + 1)
        image = images[index, ..., 0]
        label = labels[index].numpy()
        plt.imshow(image, cmap="binary")
        plt.title(label)
        plt.axis("off")
    break

InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [32,32,28,28,1] and element 21 had shape [19,32,28,28,1].

<Figure size 432x216 with 0 Axes>

### available learning data

In [159]:
print(tfds.list_builders())

['abstract_reasoning', 'aeslc', 'aflw2k3d', 'amazon_us_reviews', 'arc', 'bair_robot_pushing_small', 'beans', 'big_patent', 'bigearthnet', 'billsum', 'binarized_mnist', 'binary_alpha_digits', 'blimp', 'c4', 'caltech101', 'caltech_birds2010', 'caltech_birds2011', 'cars196', 'cassava', 'cats_vs_dogs', 'celeb_a', 'celeb_a_hq', 'cfq', 'chexpert', 'cifar10', 'cifar100', 'cifar10_1', 'cifar10_corrupted', 'citrus_leaves', 'cityscapes', 'civil_comments', 'clevr', 'cmaterdb', 'cnn_dailymail', 'coco', 'coil100', 'colorectal_histology', 'colorectal_histology_large', 'common_voice', 'cos_e', 'crema_d', 'curated_breast_imaging_ddsm', 'cycle_gan', 'deep_weeds', 'definite_pronoun_resolution', 'dementiabank', 'diabetic_retinopathy_detection', 'div2k', 'dmlab', 'downsampled_imagenet', 'dsprites', 'dtd', 'duke_ultrasound', 'emnist', 'eraser_multi_rc', 'esnli', 'eurosat', 'fashion_mnist', 'flic', 'flores', 'food101', 'forest_fires', 'gap', 'geirhos_conflict_stimuli', 'german_credit_numeric', 'gigaword', '

In [167]:
a = [[1,2],[3,4]]
for (i,j) in a:
    print(i)

1
3


3.0